#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
This is a setup.py script generated by py2applet

Usage:
    python3 setup.py py2app --packages=wx
"""

from setuptools import setup

from app_info import About

APP = ["auction46.py"]
DATA_FILES = [
    "asset/pdf-drop-target.png"
]
PLIST = {
    "CFBundleName": About.GetAppName(),
    "CFBundleShortVersionString": About.GetAppVersion(),
    "CFBundleVersion": About.GetAppVersion(),
    "CFBundleIdentifier": About.GetAppBundleStr(),
    "NSHumanReadableCopyright": About.GetAppCopyright(),
    "CFBundleDocumentTypes": [
        {
            "CFBundleTypeExtensions": [
                "pdf"
            ],
            "CFBundleTypeName": "PDF Document",
            "CFBundleTypeRole": "Viewer"
        }
    ]
}
OPTIONS = {
    "argv_emulation": False,
    "iconfile": "asset/app_icon.icns",
    "plist": PLIST
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)
