#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
This is a setup.py script generated by py2applet

Usage:
    python3 setup.py py2app --packages=wx
"""

from setuptools import setup

APP = ["auction46.py"]
DATA_FILES = [
    "asset/pdf-drop-target.png"
]
PLIST = {
    "CFBundleName": "Auction46",
    "CFBundleShortVersionString": "1.0.0",
    "CFBundleVersion": "1.0.0",
    "CFBundleIdentifier": "com.itnok.auction46",
    "NSHumanReadableCopyright": "© 2020 Simone Conti. All Rights Reserved.",
    "CFBundleDocumentTypes": [
        {
            "CFBundleTypeExtensions": [
                "pdf"
            ],
            "CFBundleTypeName": "PDF Document",
            "CFBundleTypeRole": "Viewer"
        }
    ]
}
OPTIONS = {
    "argv_emulation": False,
    "iconfile": "asset/app_icon.icns",
    "plist": PLIST
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)
